package fr.lsi.reign.domain.character.model;

import java.util.HashMap;
import java.util.Map;

/**
 * Traduit un jobId (colonne `class`) en nom lisible. Reflète l'enum e_job de rAthena
 * (server/src/common/mmo.hpp) - à resynchroniser si le serveur ajoute de nouveaux jobs.
 */
public final class JobName {

    private static final Map<Integer, String> NAMES = new HashMap<>();

    static {
        NAMES.put(0, "Novice");
        NAMES.put(1, "Swordman");
        NAMES.put(2, "Mage");
        NAMES.put(3, "Archer");
        NAMES.put(4, "Acolyte");
        NAMES.put(5, "Merchant");
        NAMES.put(6, "Thief");
        NAMES.put(7, "Knight");
        NAMES.put(8, "Priest");
        NAMES.put(9, "Wizard");
        NAMES.put(10, "Blacksmith");
        NAMES.put(11, "Hunter");
        NAMES.put(12, "Assassin");
        NAMES.put(13, "Knight 2");
        NAMES.put(14, "Crusader");
        NAMES.put(15, "Monk");
        NAMES.put(16, "Sage");
        NAMES.put(17, "Rogue");
        NAMES.put(18, "Alchemist");
        NAMES.put(19, "Bard");
        NAMES.put(20, "Dancer");
        NAMES.put(21, "Crusader 2");
        NAMES.put(22, "Wedding");
        NAMES.put(23, "Super Novice");
        NAMES.put(24, "Gunslinger");
        NAMES.put(25, "Ninja");
        NAMES.put(26, "Xmas");
        NAMES.put(27, "Summer");
        NAMES.put(28, "Hanbok");
        NAMES.put(29, "Oktoberfest");
        NAMES.put(30, "Summer 2");
        NAMES.put(4001, "Novice High");
        NAMES.put(4002, "Swordman High");
        NAMES.put(4003, "Mage High");
        NAMES.put(4004, "Archer High");
        NAMES.put(4005, "Acolyte High");
        NAMES.put(4006, "Merchant High");
        NAMES.put(4007, "Thief High");
        NAMES.put(4008, "Lord Knight");
        NAMES.put(4009, "High Priest");
        NAMES.put(4010, "High Wizard");
        NAMES.put(4011, "Whitesmith");
        NAMES.put(4012, "Sniper");
        NAMES.put(4013, "Assassin Cross");
        NAMES.put(4014, "Lord Knight 2");
        NAMES.put(4015, "Paladin");
        NAMES.put(4016, "Champion");
        NAMES.put(4017, "Professor");
        NAMES.put(4018, "Stalker");
        NAMES.put(4019, "Creator");
        NAMES.put(4020, "Clown");
        NAMES.put(4021, "Gypsy");
        NAMES.put(4022, "Paladin 2");
        NAMES.put(4023, "Baby");
        NAMES.put(4024, "Baby Swordman");
        NAMES.put(4025, "Baby Mage");
        NAMES.put(4026, "Baby Archer");
        NAMES.put(4027, "Baby Acolyte");
        NAMES.put(4028, "Baby Merchant");
        NAMES.put(4029, "Baby Thief");
        NAMES.put(4030, "Baby Knight");
        NAMES.put(4031, "Baby Priest");
        NAMES.put(4032, "Baby Wizard");
        NAMES.put(4033, "Baby Blacksmith");
        NAMES.put(4034, "Baby Hunter");
        NAMES.put(4035, "Baby Assassin");
        NAMES.put(4036, "Baby Knight 2");
        NAMES.put(4037, "Baby Crusader");
        NAMES.put(4038, "Baby Monk");
        NAMES.put(4039, "Baby Sage");
        NAMES.put(4040, "Baby Rogue");
        NAMES.put(4041, "Baby Alchemist");
        NAMES.put(4042, "Baby Bard");
        NAMES.put(4043, "Baby Dancer");
        NAMES.put(4044, "Baby Crusader 2");
        NAMES.put(4045, "Super Baby");
        NAMES.put(4046, "Taekwon");
        NAMES.put(4047, "Star Gladiator");
        NAMES.put(4048, "Star Gladiator 2");
        NAMES.put(4049, "Soul Linker");
        NAMES.put(4050, "Gangsi");
        NAMES.put(4051, "Death Knight");
        NAMES.put(4052, "Dark Collector");
        NAMES.put(4054, "Rune Knight");
        NAMES.put(4055, "Warlock");
        NAMES.put(4056, "Ranger");
        NAMES.put(4057, "Arch Bishop");
        NAMES.put(4058, "Mechanic");
        NAMES.put(4059, "Guillotine Cross");
        NAMES.put(4060, "Rune Knight T");
        NAMES.put(4061, "Warlock T");
        NAMES.put(4062, "Ranger T");
        NAMES.put(4063, "Arch Bishop T");
        NAMES.put(4064, "Mechanic T");
        NAMES.put(4065, "Guillotine Cross T");
        NAMES.put(4066, "Royal Guard");
        NAMES.put(4067, "Sorcerer");
        NAMES.put(4068, "Minstrel");
        NAMES.put(4069, "Wanderer");
        NAMES.put(4070, "Sura");
        NAMES.put(4071, "Genetic");
        NAMES.put(4072, "Shadow Chaser");
        NAMES.put(4073, "Royal Guard T");
        NAMES.put(4074, "Sorcerer T");
        NAMES.put(4075, "Minstrel T");
        NAMES.put(4076, "Wanderer T");
        NAMES.put(4077, "Sura T");
        NAMES.put(4078, "Genetic T");
        NAMES.put(4079, "Shadow Chaser T");
        NAMES.put(4080, "Rune Knight 2");
        NAMES.put(4081, "Rune Knight T 2");
        NAMES.put(4082, "Royal Guard 2");
        NAMES.put(4083, "Royal Guard T 2");
        NAMES.put(4084, "Ranger 2");
        NAMES.put(4085, "Ranger T 2");
        NAMES.put(4086, "Mechanic 2");
        NAMES.put(4087, "Mechanic T 2");
        NAMES.put(4096, "Baby Rune Knight");
        NAMES.put(4097, "Baby Warlock");
        NAMES.put(4098, "Baby Ranger");
        NAMES.put(4099, "Baby Arch Bishop");
        NAMES.put(4100, "Baby Mechanic");
        NAMES.put(4101, "Baby Guillotine Cross");
        NAMES.put(4102, "Baby Royal Guard");
        NAMES.put(4103, "Baby Sorcerer");
        NAMES.put(4104, "Baby Minstrel");
        NAMES.put(4105, "Baby Wanderer");
        NAMES.put(4106, "Baby Sura");
        NAMES.put(4107, "Baby Genetic");
        NAMES.put(4108, "Baby Shadow Chaser");
        NAMES.put(4109, "Baby Rune Knight 2");
        NAMES.put(4110, "Baby Royal Guard 2");
        NAMES.put(4111, "Baby Ranger 2");
        NAMES.put(4112, "Baby Mechanic 2");
        NAMES.put(4190, "Super Novice E");
        NAMES.put(4191, "Super Baby E");
        NAMES.put(4211, "Kagerou");
        NAMES.put(4212, "Oboro");
        NAMES.put(4215, "Rebellion");
        NAMES.put(4218, "Summoner");
        NAMES.put(4220, "Baby Summoner");
        NAMES.put(4222, "Baby Ninja");
        NAMES.put(4223, "Baby Kagerou");
        NAMES.put(4224, "Baby Oboro");
        NAMES.put(4225, "Baby Taekwon");
        NAMES.put(4226, "Baby Star Gladiator");
        NAMES.put(4227, "Baby Soul Linker");
        NAMES.put(4228, "Baby Gunslinger");
        NAMES.put(4229, "Baby Rebellion");
        NAMES.put(4238, "Baby Star Gladiator 2");
        NAMES.put(4239, "Star Emperor");
        NAMES.put(4240, "Soul Reaper");
        NAMES.put(4241, "Baby Star Emperor");
        NAMES.put(4242, "Baby Soul Reaper");
        NAMES.put(4243, "Star Emperor 2");
        NAMES.put(4244, "Baby Star Emperor 2");
        NAMES.put(4252, "Dragon Knight");
        NAMES.put(4253, "Meister");
        NAMES.put(4254, "Shadow Cross");
        NAMES.put(4255, "Arch Mage");
        NAMES.put(4256, "Cardinal");
        NAMES.put(4257, "Windhawk");
        NAMES.put(4258, "Imperial Guard");
        NAMES.put(4259, "Biolo");
        NAMES.put(4260, "Abyss Chaser");
        NAMES.put(4261, "Elemental Master");
        NAMES.put(4262, "Inquisitor");
        NAMES.put(4263, "Troubadour");
        NAMES.put(4264, "Trouvere");
        NAMES.put(4278, "Windhawk 2");
        NAMES.put(4279, "Meister 2");
        NAMES.put(4280, "Dragon Knight 2");
        NAMES.put(4281, "Imperial Guard 2");
        NAMES.put(4302, "Sky Emperor");
        NAMES.put(4303, "Soul Ascetic");
        NAMES.put(4304, "Shinkiro");
        NAMES.put(4305, "Shiranui");
        NAMES.put(4306, "Night Watch");
        NAMES.put(4307, "Hyper Novice");
        NAMES.put(4308, "Spirit Handler");
        NAMES.put(4316, "Sky Emperor 2");
        NAMES.put(4332, "Rune Knight 2nd");
        NAMES.put(4333, "Mechanic 2nd");
        NAMES.put(4334, "Guillotine Cross 2nd");
        NAMES.put(4335, "Warlock 2nd");
        NAMES.put(4336, "Archbishop 2nd");
        NAMES.put(4337, "Ranger 2nd");
        NAMES.put(4338, "Royal Guard 2nd");
        NAMES.put(4339, "Genetic 2nd");
        NAMES.put(4340, "Shadow Chaser 2nd");
        NAMES.put(4341, "Sorcerer 2nd");
        NAMES.put(4342, "Sura 2nd");
        NAMES.put(4343, "Minstrel 2nd");
        NAMES.put(4344, "Wanderer 2nd");
    }

    private JobName() {
    }

    public static String of(int jobId) {
        return NAMES.getOrDefault(jobId, "Job " + jobId);
    }
}
