FROM alpine:3.23 AS builder
WORKDIR /rathena
RUN apk add --no-cache wget git cmake make gcc g++ zlib-dev mariadb-dev ca-certificates linux-headers bash
COPY . .
RUN ./configure --enable-packetver=20220406 && make clean server

FROM alpine:3.23
WORKDIR /rathena
RUN apk add --no-cache mariadb-connector-c ca-certificates bash netcat-openbsd libstdc++ \
    && wget https://raw.githubusercontent.com/eficode/wait-for/v2.2.4/wait-for -O /bin/wait-for \
    && chmod +x /bin/wait-for
COPY --from=builder /rathena/login-server /rathena/char-server /rathena/map-server /rathena/web-server /rathena/
COPY --from=builder /rathena/conf /rathena/conf
COPY --from=builder /rathena/db /rathena/db
COPY --from=builder /rathena/npc /rathena/npc
RUN mkdir -p /rathena/save /rathena/log
ENTRYPOINT [ ]
