-- Reflet du schéma réel de la table `login` de rAthena (server/sql-files/main.sql),
-- pour valider account.orm.xml contre une structure fidèle plutôt qu'un schéma généré par Hibernate.
DROP TABLE IF EXISTS login;

CREATE TABLE login (
  account_id int unsigned NOT NULL AUTO_INCREMENT,
  userid varchar(23) NOT NULL DEFAULT '',
  user_pass varchar(32) NOT NULL DEFAULT '',
  sex enum('M','F','S') NOT NULL DEFAULT 'M',
  email varchar(39) NOT NULL DEFAULT '',
  group_id tinyint NOT NULL DEFAULT 0,
  state int unsigned NOT NULL DEFAULT 0,
  unban_time int unsigned NOT NULL DEFAULT 0,
  expiration_time int unsigned NOT NULL DEFAULT 0,
  logincount mediumint unsigned NOT NULL DEFAULT 0,
  lastlogin datetime,
  last_ip varchar(100) NOT NULL DEFAULT '',
  birthdate date,
  character_slots tinyint unsigned NOT NULL DEFAULT 0,
  pincode varchar(4) NOT NULL DEFAULT '',
  pincode_change int unsigned NOT NULL DEFAULT 0,
  vip_time int unsigned NOT NULL DEFAULT 0,
  old_group tinyint NOT NULL DEFAULT 0,
  web_auth_token varchar(17),
  web_auth_token_enabled tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (account_id)
);

-- Reflet complet du schéma réel de la table `char` de rAthena (server/sql-files/main.sql). Table
-- quotée car `char` est un mot réservé SQL. character.orm.xml mappe désormais (quasi) toutes les
-- colonnes, d'où le besoin de les refléter toutes ici plutôt qu'un sous-ensemble.
DROP TABLE IF EXISTS `char`;

CREATE TABLE `char` (
  char_id int unsigned NOT NULL AUTO_INCREMENT,
  account_id int unsigned NOT NULL DEFAULT 0,
  char_num tinyint NOT NULL DEFAULT 0,
  name varchar(30) NOT NULL DEFAULT '',
  class smallint unsigned NOT NULL DEFAULT 0,
  base_level smallint unsigned NOT NULL DEFAULT 1,
  job_level smallint unsigned NOT NULL DEFAULT 1,
  base_exp bigint unsigned NOT NULL DEFAULT 0,
  job_exp bigint unsigned NOT NULL DEFAULT 0,
  zeny int unsigned NOT NULL DEFAULT 0,
  str smallint unsigned NOT NULL DEFAULT 0,
  agi smallint unsigned NOT NULL DEFAULT 0,
  vit smallint unsigned NOT NULL DEFAULT 0,
  `int` smallint unsigned NOT NULL DEFAULT 0,
  dex smallint unsigned NOT NULL DEFAULT 0,
  luk smallint unsigned NOT NULL DEFAULT 0,
  pow smallint unsigned NOT NULL DEFAULT 0,
  sta smallint unsigned NOT NULL DEFAULT 0,
  wis smallint unsigned NOT NULL DEFAULT 0,
  spl smallint unsigned NOT NULL DEFAULT 0,
  con smallint unsigned NOT NULL DEFAULT 0,
  crt smallint unsigned NOT NULL DEFAULT 0,
  max_hp int unsigned NOT NULL DEFAULT 0,
  hp int unsigned NOT NULL DEFAULT 0,
  max_sp int unsigned NOT NULL DEFAULT 0,
  sp int unsigned NOT NULL DEFAULT 0,
  max_ap int unsigned NOT NULL DEFAULT 0,
  ap int unsigned NOT NULL DEFAULT 0,
  status_point int unsigned NOT NULL DEFAULT 0,
  skill_point int unsigned NOT NULL DEFAULT 0,
  trait_point int unsigned NOT NULL DEFAULT 0,
  `option` int NOT NULL DEFAULT 0,
  karma tinyint NOT NULL DEFAULT 0,
  manner smallint NOT NULL DEFAULT 0,
  party_id int unsigned NOT NULL DEFAULT 0,
  guild_id int unsigned NOT NULL DEFAULT 0,
  pet_id int unsigned NOT NULL DEFAULT 0,
  homun_id int unsigned NOT NULL DEFAULT 0,
  elemental_id int unsigned NOT NULL DEFAULT 0,
  hair tinyint unsigned NOT NULL DEFAULT 0,
  hair_color smallint unsigned NOT NULL DEFAULT 0,
  clothes_color smallint unsigned NOT NULL DEFAULT 0,
  body smallint unsigned NOT NULL DEFAULT 0,
  weapon smallint unsigned NOT NULL DEFAULT 0,
  shield smallint unsigned NOT NULL DEFAULT 0,
  head_top smallint unsigned NOT NULL DEFAULT 0,
  head_mid smallint unsigned NOT NULL DEFAULT 0,
  head_bottom smallint unsigned NOT NULL DEFAULT 0,
  robe smallint unsigned NOT NULL DEFAULT 0,
  last_map varchar(11) NOT NULL DEFAULT '',
  last_x smallint unsigned NOT NULL DEFAULT 53,
  last_y smallint unsigned NOT NULL DEFAULT 111,
  last_instanceid int unsigned NOT NULL DEFAULT 0,
  save_map varchar(11) NOT NULL DEFAULT '',
  save_x smallint unsigned NOT NULL DEFAULT 53,
  save_y smallint unsigned NOT NULL DEFAULT 111,
  partner_id int unsigned NOT NULL DEFAULT 0,
  online tinyint NOT NULL DEFAULT 0,
  father int unsigned NOT NULL DEFAULT 0,
  mother int unsigned NOT NULL DEFAULT 0,
  child int unsigned NOT NULL DEFAULT 0,
  fame int unsigned NOT NULL DEFAULT 0,
  rename smallint unsigned NOT NULL DEFAULT 0,
  delete_date int unsigned NOT NULL DEFAULT 0,
  moves int unsigned NOT NULL DEFAULT 0,
  unban_time int unsigned NOT NULL DEFAULT 0,
  font tinyint unsigned NOT NULL DEFAULT 0,
  uniqueitem_counter int unsigned NOT NULL DEFAULT 0,
  sex enum('M','F') NOT NULL,
  hotkey_rowshift tinyint unsigned NOT NULL DEFAULT 0,
  hotkey_rowshift2 tinyint unsigned NOT NULL DEFAULT 0,
  clan_id int unsigned NOT NULL DEFAULT 0,
  last_login datetime,
  title_id int unsigned NOT NULL DEFAULT 0,
  show_equip tinyint unsigned NOT NULL DEFAULT 0,
  inventory_slots smallint NOT NULL DEFAULT 100,
  body_direction tinyint unsigned NOT NULL DEFAULT 0,
  disable_call tinyint unsigned NOT NULL DEFAULT 0,
  disable_partyinvite tinyint unsigned NOT NULL DEFAULT 0,
  disable_showcostumes tinyint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (char_id),
  UNIQUE KEY name_key (name),
  KEY account_id_key (account_id)
);
