package fr.lsi.reign.exposition.character.dto;

import fr.lsi.reign.domain.character.model.GameCharacter;
import fr.lsi.reign.domain.character.model.JobName;
import java.time.LocalDateTime;

/**
 * Reprend (quasi) toutes les colonnes de GameCharacter : vue brute exhaustive pour le panneau de
 * focus côté site, en attendant de savoir ce qui vaut la peine d'être mis en forme visuellement.
 */
public record CharacterResponse(
        Long charId,
        int charNum,
        String name,
        int jobId,
        String jobName,
        int baseLevel,
        int jobLevel,
        long baseExp,
        long jobExp,
        long zeny,
        int str,
        int agi,
        int vit,
        int intelligence,
        int dex,
        int luk,
        int pow,
        int sta,
        int wis,
        int spl,
        int con,
        int crt,
        int maxHp,
        int hp,
        int maxSp,
        int sp,
        int maxAp,
        int ap,
        int statusPoint,
        int skillPoint,
        int traitPoint,
        int option,
        int karma,
        int manner,
        int partyId,
        int guildId,
        int petId,
        int homunId,
        int elementalId,
        int hair,
        int hairColor,
        int clothesColor,
        int body,
        int weapon,
        int shield,
        int headTop,
        int headMid,
        int headBottom,
        int robe,
        String lastMap,
        int lastX,
        int lastY,
        int lastInstanceId,
        String saveMap,
        int saveX,
        int saveY,
        int partnerId,
        boolean online,
        int father,
        int mother,
        int child,
        int fame,
        int rename,
        long deleteDate,
        int moves,
        int unbanTime,
        int font,
        int uniqueItemCounter,
        String sex,
        int hotkeyRowshift,
        int hotkeyRowshift2,
        int clanId,
        LocalDateTime lastLogin,
        int titleId,
        int showEquip,
        int inventorySlots,
        int bodyDirection,
        int disableCall,
        int disablePartyInvite,
        int disableShowCostumes) {

    public static CharacterResponse from(GameCharacter c) {
        return new CharacterResponse(
                c.getCharId(),
                c.getCharNum(),
                c.getName(),
                c.getJobId(),
                JobName.of(c.getJobId()),
                c.getBaseLevel(),
                c.getJobLevel(),
                c.getBaseExp(),
                c.getJobExp(),
                c.getZeny(),
                c.getStr(),
                c.getAgi(),
                c.getVit(),
                c.getIntelligence(),
                c.getDex(),
                c.getLuk(),
                c.getPow(),
                c.getSta(),
                c.getWis(),
                c.getSpl(),
                c.getCon(),
                c.getCrt(),
                c.getMaxHp(),
                c.getHp(),
                c.getMaxSp(),
                c.getSp(),
                c.getMaxAp(),
                c.getAp(),
                c.getStatusPoint(),
                c.getSkillPoint(),
                c.getTraitPoint(),
                c.getOption(),
                c.getKarma(),
                c.getManner(),
                c.getPartyId(),
                c.getGuildId(),
                c.getPetId(),
                c.getHomunId(),
                c.getElementalId(),
                c.getHair(),
                c.getHairColor(),
                c.getClothesColor(),
                c.getBody(),
                c.getWeapon(),
                c.getShield(),
                c.getHeadTop(),
                c.getHeadMid(),
                c.getHeadBottom(),
                c.getRobe(),
                c.getLastMap(),
                c.getLastX(),
                c.getLastY(),
                c.getLastInstanceId(),
                c.getSaveMap(),
                c.getSaveX(),
                c.getSaveY(),
                c.getPartnerId(),
                c.isOnline(),
                c.getFather(),
                c.getMother(),
                c.getChild(),
                c.getFame(),
                c.getRename(),
                c.getDeleteDate(),
                c.getMoves(),
                c.getUnbanTime(),
                c.getFont(),
                c.getUniqueItemCounter(),
                c.getSex() == null ? null : c.getSex().name(),
                c.getHotkeyRowshift(),
                c.getHotkeyRowshift2(),
                c.getClanId(),
                c.getLastLogin(),
                c.getTitleId(),
                c.getShowEquip(),
                c.getInventorySlots(),
                c.getBodyDirection(),
                c.getDisableCall(),
                c.getDisablePartyInvite(),
                c.getDisableShowCostumes());
    }
}
